// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_8Qhjq3_v2EwOY_4oEJNVMzjDHzBK8M',
    appId: '1:1080335586737:web:dbb53236908923ca285990',
    messagingSenderId: '1080335586737',
    projectId: 'unichat-d6dd5',
    authDomain: 'unichat-d6dd5.firebaseapp.com',
    databaseURL: 'https://unichat-d6dd5-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-d6dd5.appspot.com',
    measurementId: 'G-T55S4W7PNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeA6hrsuqVsRlDwgcqqNW_yrCNylecAB4',
    appId: '1:1080335586737:android:3ae30feedc48a768285990',
    messagingSenderId: '1080335586737',
    projectId: 'unichat-d6dd5',
    databaseURL: 'https://unichat-d6dd5-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-d6dd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBa2Xmmcnmt_aGU6ugs8K_7rrGCbUuGEc',
    appId: '1:1080335586737:ios:9bfbd5a3e1e51096285990',
    messagingSenderId: '1080335586737',
    projectId: 'unichat-d6dd5',
    databaseURL: 'https://unichat-d6dd5-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-d6dd5.appspot.com',
    iosClientId: '1080335586737-159fd65chht1ei7limchgj5td229na5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.unichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBa2Xmmcnmt_aGU6ugs8K_7rrGCbUuGEc',
    appId: '1:1080335586737:ios:0801f707a213b69b285990',
    messagingSenderId: '1080335586737',
    projectId: 'unichat-d6dd5',
    databaseURL: 'https://unichat-d6dd5-default-rtdb.firebaseio.com',
    storageBucket: 'unichat-d6dd5.appspot.com',
    iosClientId: '1080335586737-g7i83uva78qh2mn6e7j3apgb2clog6gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.unichat.RunnerTests',
  );
}
